import type { Ticket, Comment } from '../../app/shared/types';

export const mockTickets: Ticket[] = [
  {
    id: 'ticket_1',
    categoryId: 'cat_1',
    subCategoryId: 'subcat_1',
    userId: 'user_1',
    title: 'Laptop screen flickering intermittently',
    description: 'My laptop screen has been flickering on and off randomly throughout the day',
    content: 'The issue started yesterday morning. The screen flickers every 10-15 minutes, sometimes going completely black for a few seconds. It\'s making it very difficult to work. I\'ve tried restarting the laptop multiple times but the problem persists. The laptop is a Dell XPS 13 from 2022.',
    tagIds: ['tag_urgent', 'tag_hardware'],
    agentId: 'agent_1',
    status: 'in_progress',
    priority: 'high',
    severity: 'high',
    createdAt: '2024-01-25T09:30:00Z',
    updatedAt: '2024-01-25T14:20:00Z',
  },
  {
    id: 'ticket_2',
    categoryId: 'cat_2',
    subCategoryId: 'subcat_5',
    userId: 'user_2',
    title: 'Cannot reset password - email not received',
    description: 'I\'m not receiving the password reset email',
    content: 'I\'ve been trying to reset my password for the past hour. I click on "Forgot Password" and enter my email address, but I never receive the reset email. I\'ve checked my spam folder and it\'s not there either. My email is sarah.johnson@company.com. Please help me regain access to my account.',
    tagIds: ['tag_urgent'],
    agentId: 'agent_2',
    status: 'waiting_for_agent',
    priority: 'medium',
    severity: 'medium',
    createdAt: '2024-01-24T16:45:00Z',
    updatedAt: '2024-01-25T08:15:00Z',
  },
  {
    id: 'ticket_3',
    categoryId: 'cat_3',
    subCategoryId: 'subcat_8',
    userId: 'user_3',
    title: 'Submit button not working on contact form',
    description: 'The submit button on the contact form appears broken',
    content: 'When I try to submit the contact form on the website, clicking the "Submit" button doesn\'t do anything. There\'s no loading indicator, no success message, and no error message. The form just sits there. I\'ve tried this on both Chrome and Firefox with the same result. This is preventing me from contacting potential clients.',
    tagIds: ['tag_ui', 'tag_web'],
    agentId: 'agent_3',
    status: 'open',
    priority: 'high',
    severity: 'medium',
    createdAt: '2024-01-23T11:20:00Z',
    updatedAt: '2024-01-24T09:30:00Z',
  },
  {
    id: 'ticket_4',
    categoryId: 'cat_4',
    subCategoryId: 'subcat_11',
    userId: 'user_1',
    title: 'Request for dark mode theme',
    description: 'Would love to have a dark mode option for the application',
    content: 'Hi team! I spend a lot of time using the application, especially during evening hours. A dark mode theme would be incredibly helpful for reducing eye strain. Many users in our department have expressed interest in this feature. It would be great if users could toggle between light and dark themes in their profile settings.',
    tagIds: ['tag_enhancement', 'tag_ui'],
    status: 'new',
    priority: 'low',
    severity: 'low',
    createdAt: '2024-01-22T14:10:00Z',
    updatedAt: '2024-01-22T14:10:00Z',
  },
  {
    id: 'ticket_5',
    categoryId: 'cat_1',
    subCategoryId: 'subcat_3',
    userId: 'user_2',
    title: 'VPN connection keeps dropping',
    description: 'VPN disconnects every 30 minutes requiring manual reconnection',
    content: 'Our VPN connection has been very unstable lately. It disconnects approximately every 30 minutes, which is disruptive to my workflow. I have to manually reconnect each time, and sometimes it takes several attempts to establish a stable connection. This started happening about a week ago. I\'m using the company-provided VPN client on Windows 11.',
    tagIds: ['tag_network', 'tag_vpn'],
    agentId: 'agent_1',
    status: 'assigned',
    priority: 'medium',
    severity: 'medium',
    createdAt: '2024-01-21T10:15:00Z',
    updatedAt: '2024-01-25T16:45:00Z',
  },
  {
    id: 'ticket_6',
    categoryId: 'cat_5',
    subCategoryId: 'subcat_13',
    userId: 'user_3',
    title: 'Question about health insurance coverage',
    description: 'Need clarification on dental coverage for dependents',
    content: 'I recently added my spouse to my health insurance plan and I want to understand what dental coverage is included for dependents. The benefits documentation is a bit unclear about the specific coverage limits and co-pays for family members. Could someone from HR provide detailed information about our dental benefits for dependents?',
    tagIds: ['tag_benefits', 'tag_family'],
    agentId: 'agent_4',
    status: 'waiting_for_customer',
    priority: 'low',
    severity: 'low',
    createdAt: '2024-01-20T13:25:00Z',
    updatedAt: '2024-01-24T11:10:00Z',
  },
  {
    id: 'ticket_7',
    categoryId: 'cat_6',
    subCategoryId: 'subcat_15',
    userId: 'user_1',
    title: 'Payment failed for monthly subscription',
    description: 'Credit card payment was declined but card is valid',
    content: 'My monthly subscription payment failed yesterday, but I know my credit card is valid and has sufficient funds. I used the same card successfully for other purchases today. The error message just says "Payment declined" without any specific reason. My subscription is now showing as suspended. Please help resolve this payment issue.',
    tagIds: ['tag_payment', 'tag_urgent'],
    agentId: 'agent_2',
    status: 'resolved',
    priority: 'high',
    severity: 'medium',
    createdAt: '2024-01-19T08:40:00Z',
    updatedAt: '2024-01-21T15:30:00Z',
    closedAt: '2024-01-21T15:30:00Z',
  },
  {
    id: 'ticket_8',
    categoryId: 'cat_3',
    subCategoryId: 'subcat_9',
    userId: 'user_2',
    title: 'Application extremely slow to load',
    description: 'Dashboard takes over 2 minutes to load completely',
    content: 'The application dashboard has become extremely slow over the past few days. It takes over 2 minutes to fully load, and sometimes it times out completely. This is affecting my productivity significantly. Other team members have reported similar issues. The problem seems to be worse during peak hours (9 AM - 5 PM). I\'ve cleared my browser cache and tried different browsers, but the issue persists.',
    tagIds: ['tag_performance', 'tag_dashboard'],
    agentId: 'agent_3',
    status: 'closed',
    priority: 'critical',
    severity: 'high',
    createdAt: '2024-01-18T07:20:00Z',
    updatedAt: '2024-01-20T12:45:00Z',
    closedAt: '2024-01-20T12:45:00Z',
  },
];

export const mockComments: Comment[] = [
  // Comments for ticket_1 (Laptop screen flickering)
  {
    id: 'comment_1',
    ticketId: 'ticket_1',
    userId: 'agent_1',
    content: 'Hi John, I\'ve received your ticket about the screen flickering issue. This sounds like it could be a hardware problem with the display panel or graphics driver. Let\'s start with some basic troubleshooting steps.',
    createdAt: '2024-01-25T10:15:00Z',
    updatedAt: '2024-01-25T10:15:00Z',
  },
  {
    id: 'comment_2',
    ticketId: 'ticket_1',
    userId: 'agent_1',
    content: 'Please try the following steps: 1) Update your graphics drivers 2) Check if the issue occurs in safe mode 3) Try connecting an external monitor to see if the problem persists. Let me know the results.',
    createdAt: '2024-01-25T10:20:00Z',
    updatedAt: '2024-01-25T10:20:00Z',
  },
  {
    id: 'comment_3',
    ticketId: 'ticket_1',
    userId: 'user_1',
    content: 'Thanks Alex! I updated the graphics drivers and the flickering seems to have reduced significantly. I\'ll monitor it for the rest of the day and update you if it happens again.',
    createdAt: '2024-01-25T14:20:00Z',
    updatedAt: '2024-01-25T14:20:00Z',
  },

  // Comments for ticket_2 (Password reset)
  {
    id: 'comment_4',
    ticketId: 'ticket_2',
    userId: 'agent_2',
    content: 'Hi Sarah, I can see that there have been multiple password reset attempts for your account. Let me check our email logs to see what\'s happening with the reset emails.',
    createdAt: '2024-01-24T17:30:00Z',
    updatedAt: '2024-01-24T17:30:00Z',
  },
  {
    id: 'comment_5',
    ticketId: 'ticket_2',
    userId: 'agent_2',
    content: 'I found the issue - your email was marked as bounced in our system due to a temporary delivery issue yesterday. I\'ve cleared the bounce flag and sent you a new password reset email. Please check your inbox.',
    createdAt: '2024-01-25T08:15:00Z',
    updatedAt: '2024-01-25T08:15:00Z',
  },

  // Comments for ticket_7 (Payment failed)
  {
    id: 'comment_6',
    ticketId: 'ticket_7',
    userId: 'agent_2',
    content: 'Hi John, I\'ve looked into your payment issue. It appears there was a temporary problem with our payment processor yesterday. I\'ve manually processed your payment and reactivated your subscription.',
    createdAt: '2024-01-19T15:20:00Z',
    updatedAt: '2024-01-19T15:20:00Z',
  },
  {
    id: 'comment_7',
    ticketId: 'ticket_7',
    userId: 'user_1',
    content: 'Perfect! I can see my subscription is active again. Thank you for the quick resolution, Emily!',
    createdAt: '2024-01-19T16:10:00Z',
    updatedAt: '2024-01-19T16:10:00Z',
  },
  {
    id: 'comment_8',
    ticketId: 'ticket_7',
    userId: 'agent_2',
    content: 'Great! I\'ve also set up monitoring to prevent similar payment processor issues in the future. Your account should work smoothly going forward. Marking this as resolved.',
    createdAt: '2024-01-21T15:30:00Z',
    updatedAt: '2024-01-21T15:30:00Z',
  },
];